### PR TITLE
Url link resolver

### PR DESCRIPTION
**Pull request by Simply007**
Pull request for the issue:
https://github.com/Kentico/delivery-sdk-php/issues/7

### CODE REVIEW

**Comment by Simply007** [comment]
Do we want to implement [KenticoCloud.Delivery.ContentLinkResolver.ResolveContentLinks](https://github.com/Kentico/delivery-sdk-net/blob/master/KenticoCloud.Delivery/ContentLinks/ContentLinkResolver.cs) use two methods?
- ResolveLinkUrl
- ResolveBrokenLinkUrl - in case link is not in links property of the element (currently not implemented), but no problem to implement 

Do you have any hint, how to fix codeclimate check?

**Comment by dusekdan** [comment]
As for the codeclimate checks, from what I can see the problem is in unused parameters.  Maybe marking them as optional in your implementations (or removing/using them) would pass the codeclimate check?

**Comment by petrsvihlik** [comment]
@Simply007 
- ResolveContentLinks I'd stick to the patter as it's also implemented in the Java SDK...

**Comment by Simply007** [comment]
@petrsvihlik - Please take a look on codeclimate changes

**Comment by petrsvihlik** [comment]
@Simply007 if I understand it correctly, the problematic parameters are present just as a preparation for #8 . If my assumption is correct, just remove the params for now.

**Pull request merged**
