### PR TITLE
Create api documentation

### PR DESCRIPTION
**Pull request by RadoslavCap**
Generated documentation. Only small amount of TODOs (in comparison with original state) left. It's ready for merge with master.

### CODE REVIEW

**Comment by dusekdan** [comment]
Nice job, Radek! I think that while we can certainly benefit from commentaries you added, it is not necessary to add generated documentation to the repository. I already checked delivery-sdk-net repository and documentation is not present. Will @petrsvihlik decide where to put it?

**Comment by RadoslavCap** [comment]
To have generated documentation in a repo was an original requirement if I remember it well. I have no preference for it.

**Comment by petrsvihlik** [comment]
i have no problem with storing the docu in this repo...i have the feeling that it's quite common..or is it not?

**Comment by dusekdan** [comment]
It's OK with me as well then, I was not sure at first as 409 codeclimate checks failed so I checked whether we store documentation for .net sdk. So I guess it's okay to merge now? :+1: :)

**Pull request merged**
